# Predict water use from energy use data


# Preparation
```{r}
# data <-
#   fread("Data/water_energy_MW.csv") %>%
#   .[, mean_w_to_e := mean(w_to_e, na.rm = TRUE), by = nrdname] %>%
#   .[, water_est := kwh * mean_w_to_e / 12]

# saveRDS(data, "Data/water_energy_MW.rds")

data <- readRDS("Data/water_energy_MW.rds")
```


# Naive water use prediction

```{r}
ggplot(data = data[nrdname != "Twin Platte", ]) +
  geom_point(aes(y = volaf, x = water_est), size = 0.1) +
  facet_grid(year ~ nrdname) +
  geom_abline(intercept = 0, slopw = 1) +
  xlab("Water Use Estimates Based on Energy Use (acre-feet)") +
  ylab("Observed Water Use (acre-feet)") +
  theme(
    legend.position = "bottom"
  )
ggsave("./Graphs/how_good_energy.pdf", height = 10, width = 6)

ggplot(data = data[!is.na(w_to_e) & nrdname != "Twin Platte", ]) +
  geom_boxplot(aes(y = w_to_e, x = factor(year)), alpha = 0.3) +
  facet_grid(nrdname ~ .) +
  ylab("Water (acre-feet)/Energy (kwh)") +
  xlab("Year")

ggsave("./Graphs/water_to_energy.pdf")

ggplot(data = data[!is.na(w_to_e) & nrdname != "Twin Platte", ]) +
  geom_density(aes(x = w_to_e, fill = factor(year)), alpha = 0.3) +
  facet_grid(nrdname ~ .) +
  ylab("Water (acre-feet)/Energy (kwh)") +
  xlab("Year")

ggsave("./Graphs/water_to_energy.pdf")
```